### ISSUE TITLE
Enhancement to rendering multiple examples

### ISSUE THREAD

**Issue by sichvoge** [wdullaer/raml2html-slate-theme#12]
Is there any possibility to have tabs when someone defined multiple examples with the name each tab reflecting the key name of an example? For example:

```yaml
examples: 
        test1: |
          {
            "address_country": "terte",
            "address_locality": "ertth",
            "address_region": "dgere",
            "postal_code": "sdfsdg",
            "street_address": "gdfgdfg"
          }
        test2: |
          {
            "address_country": "terte",
            "address_locality": "ertth",
            "address_region": "dgere",
            "postal_code": "sdfsdg",
            "street_address": "gdfgdfg"
          }
```

I would expect two tabs called `test1` and `test2` with the respective content.

At the moment each example is put under the other.

![image](https://cloud.githubusercontent.com/assets/498114/26447303/de45126a-413f-11e7-81ac-a5fdb5c64c41.png)
