### ISSUE TITLE
Show the display name for a method

### ISSUE THREAD

**Issue by rzane** [wdullaer/raml2html-slate-theme#22]
Given the following YAML:

```yaml
/users:
  displayName: Users

  post:
    displayName: Create a user
```

I'd expect to see the following hierarchy in the table of contents:

```
+ Users
  + Create a user
```

As a result, I think there should be an additional `if` statement here: 
* https://github.com/wdullaer/raml2html-slate-theme/blob/master/templates/resource.nunjucks#L11
* https://github.com/wdullaer/raml2html-slate-theme/blob/master/templates/resource.nunjucks#L71

**Comment by wdullaer** [comment]
That is exactly what the code does no?
I tried here with some reference schemas I use and it properly renders the displayName in both the titles and the TOC if it is present

**Comment by rzane** [comment]
Hmm... that doesn't seem to work that way for me. See the example below:

```yaml
#%RAML 1.0
---
/users:
  displayName: Users

  post:
    displayName: Create a user
```

![screen shot 2017-08-01 at 1 38 04 pm](https://user-images.githubusercontent.com/2731572/28838547-ac7f35b2-76be-11e7-93b1-12935cfc7278.png)

I created a fork that works as I'd expect. Happy to submit as a PR, if it's amenable. Here's the diff: https://github.com/wdullaer/raml2html-slate-theme/compare/master...ThriveTRM:master
