### ISSUE TITLE
Add support for x-www-form-urlencoded

### ISSUE THREAD

**Issue by chickahoona** [wdullaer/raml2html-slate-theme#93]
Currently it is not possible to specify parameters and "x-www-form-urlencoded" them.

As an example:

```
body:
  application/x-www-form-urlencoded:
    properties:
      name:
        description: name on account
        type: string
        example: Naruto Uzumaki
      gender:
        enum: ["male", "female"]

```

This renders to:

![image](https://user-images.githubusercontent.com/8075146/75141611-9e3b1280-56f1-11ea-8adb-5872c751be3e.png)

Instead it should show an example like:

```
curl -d "name=Naruto Uzumaki&gender=male" -X POST https://example.com/oauth2/token
```

This is especially problematic, as one wants to describe an oauth flow, which "x-www-form-urlencoded" its parameters.

Sidenote: It was also requested here: https://github.com/raml2html/raml2html/issues/386
